### ISSUE TITLE
Allow export via Registrations page

### ISSUE THREAD

**Issue by monicabritton** [amschaal/django-ezreg#49]
Currently, I can only export (csv/xls) from within a particular event.

I want to be able to do the exact same export across events, from the Registrations page.

For example, if I go to the Registrations page and filter by say,  "Payment Status" I want to be able to export all the info related to those individuals.

Secondarily, after the above has been added, it would be great to be able to add another field to the export for dates, so I could export all the individuals across multiple events during a particular time interval.

Merci!

**Comment by amschaal** [comment]
I've mostly implemented this.  Basically, it will export whatever is currently being filtered.  Also, because some fields will be different between different events, I'm only exporting fields that will always be the same.

I have yet to add the date filtering.  I'll add that, polish things up, then get it in production.

**Comment by amschaal** [comment]
Everything has been added and moved to production.  Closing this issue.  Feel free to reopen if I missed anything.
